from enum import Enum

class PromptType(Enum):
    ZERO_SHOT_PROMPT = "ZERO_SHOT_PROMPT"
    FEW_SHOT_PROMPT = "FEW_SHOT_PROMPT"
    CHAIN_OF_THOUGHT = "CHAIN_OF_THOUGHT"
    STYLE_SPECIFIC_PROMPTING = "STYLE_SPECIFIC_PROMPTING"
    LENGHT_LIMITATION_PROMPTING = "LENGHT_LIMITATION_PROMPTING"
    STEP_BY_STEP_INSTRUCTION_PROMPTING = "STEP_BY_STEP_INSTRUCTION_PROMPTING"
    DEFINITION_EXEMPLIFICATION = "DEFINITION_EXEMPLIFICATION"
